# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "xhci_pci_renesas" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/134b9e75-f91c-4429-b05f-69c4cdbd9163";
      fsType = "ext4";
    };

#  fileSystems."/boot" =
#    { device = "systemd-1";
#      fsType = "autofs";
#    };

  fileSystems."/boot" = {
  device = "/dev/disk/by-uuid/F389-BC06";
  fsType = "vfat";
  };

#  fileSystems."/home" =
#    { device = "/dev/disk/by-uuid/e03487f4-e5d0-4004-896e-c94333458a7c";
#      fsType = "xfs";
#    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
